services:
  autobacklog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: autobacklog
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: autobacklog
  redis:
      image: redis:8